### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by Cooperr06** [Cooperr06/q11-doodle-jump-project#1]
Integrate the MariaDB database using the MariaDB JDBC and implement methods for storing, updating and querying objects like Account and Skin. ToDo's:

- [x] Implement DatabaseManager class with methods
- [x] Implement required classes (Account)
- [x] Write initialisation script for the database which is being executed when the program starts

**Comment by Sarao7** [comment]
Ok bin ich jetzt richtig? xD Also ich könnte versuchen addSkin oder removeSkin zu implementieren

**Comment by Cooperr06** [comment]
> Ok bin ich jetzt richtig? xD Also ich könnte versuchen addSkin oder removeSkin zu implementieren

Passt, kannst dich als Assignee eintragen 👍

**Comment by Cooperr06** [comment]
Ich würde dann auch die Klassen "Account" und "Skin" übernehmen, ist ja nicht viel.

**Comment by Bene05** [comment]
Ich würde mich um den Highscore kümmern

**Comment by Superiron29** [comment]
Implementierung der "deductCoins" Methode

**Comment by Cooperr06** [comment]
Ich kümmere mich noch um den Avatar in der DatabaseManager Klasse
