### ISSUE TITLE
Implement "PlatformManager" class

### ISSUE THREAD

**Issue by Cooperr06** [Cooperr06/q11-doodle-jump-project#11]
Implement the "PlatformManager" class using the singleton pattern. ToDo's:

- [x] Implement constructor and attributes
- [ ] Implement the methods for generating platforms

**Comment by Niclas02** [comment]
Platform Manager und Enemy Manager

**Comment by Cooperr06** [comment]
Wir wollen erstmal die Enemies weglassen, ich editiere auch gleich noch den Issue.

**Comment by Niclas02** [comment]
Ich mach erstmal den Plattform Manager, an sich ist aber Enemy Manager dasselbe. Soll der Plattform Manager nur die Plattformen erzeugen, oder auch direkt die Plattformen in die liste einfügen? Und wenn ja übernimmt der Plattform Manager das Löschen, sofern die Plattform den Bildschirm verlässt?

**Comment by Cooperr06** [comment]
Das ist eben noch nicht klar, da wir auch noch nicht wissen, wie die Generatoren wissen sollen, wann eine Plattform nicht mehr im Fenster ist. Den EnemyManager kannst du wie gesagt weglassen, da wir erstmal keine Enemies mit einbauen wollen.

**Comment by Niclas02** [comment]
Man kann ja machen if platform y <= Auflösung y - 1/2 Auflösung y  -> delete Platform

**Comment by Cooperr06** [comment]
Dafür bräuchte man halt die Auflösung, weshalb wir schon diskutiert haben und ihn auch fragen wollen, ob wir vllt eine Config Klasse erstellen, die diese ganzen Daten in public static Attributen verwaltet.

**Comment by Cooperr06** [comment]
Linked branch: [11-implement-platformmanager-class](https://github.com/Cooperr06/q11-doodle-jump-project/tree/11-implement-platformmanager-class) (due to bug in GitHub)
