### ISSUE TITLE
Implement utility classes

### ISSUE THREAD

**Issue by Cooperr06** [Cooperr06/q11-doodle-jump-project#4]
ToDo's:

- [ ] Implement the following classes:
- Position
- Movable (interface)
- Avatar
- Enemy (abstract)
- Platform

**Comment by Niclas02** [comment]
Position und Platform

**Comment by Meicky** [comment]
Avatar und Platform

**Comment by Niclas02** [comment]
Mache Enemy

**Comment by Cooperr06** [comment]
Enemy wird vorerst weggelassen
