### ISSUE TITLE
Differentiate between Main screen state and Game state

### ISSUE THREAD

**Issue by Cooperr06** [Cooperr06/q11-doodle-jump-project#42]
- [x] Add Skin selection
- [ ] Add "Press Enter to start" text
- [x] Add Database Integration

**Comment by Cooperr06** [comment]
I am doing the actual Database Integration, rest is free for all

**Comment by Darrell4** [comment]
I am doing the handling in InputManager

**Comment by Cooperr06** [comment]
Edited, Skins are added in other issue
