### ISSUE TITLE
Implement "Renderer" class

### ISSUE THREAD

**Issue by Cooperr06** [Cooperr06/q11-doodle-jump-project#5]
Implement the "Renderer" class with its methods and attributes using the Swing library. ToDo's:

- [x] Implement the "Renderer" class using the Swing library

**Comment by therealnix** [comment]
Ich lese mich rein und implementiere die Klasse bis incl. Mittwoch.
Oder wie Colin sagen würde : _I read myself inside and implement the Class till Wednesday ( :_
